### ISSUE TITLE
Resolving to 523 

### ISSUE THREAD

**Issue by rawleyfowler** [Raku/setup-raku#31]
![image](https://github.com/Raku/setup-raku/assets/75388349/e3d9e56b-e555-4273-978b-0d65056c6f20)

Recently all of my `latest` raku setups have failed with 523. Not sure if this is GitHub, this repo, or what. Thanks!

**Comment by skaji** [comment]
```
❯ curl -v https://rakudo.org/dl/rakudo -o /dev/null -s
*   Trying [2606:4700:20::681a:7d6]:443...
* Connected to rakudo.org (2606:4700:20::681a:7d6) port 443 (#0)
...
< HTTP/2 523
```

This is an issue for rakudo.org, not setup-raku.

**Comment by rawleyfowler** [comment]
@skaji Makes sense. Thank you!
