### ISSUE TITLE
Workflows seamingly failing for no reason

### ISSUE THREAD

**Issue by rawleyfowler** [Raku/setup-raku#33]
After the outtage of [rakudo.org](https://rakudo.org), workflows have yet to come back up. I'm seeing [a lot of fails](https://github.com/rawleyfowler/Humming-Bird/actions/runs/6860526760/job/18654507654), not sure if this is still the sites fault or, if something changed and the workflow will have to adapt to it.

Thanks!

**Comment by skaji** [comment]
Running multiple jobs at the same time makes debugging difficult. Please run only one job at a time or specify fail-fast: false for execution.

**Comment by skaji** [comment]
After trying several times in my local environment, it seemed that the download was failing because the connection was getting cut off partway.

```
❯ curl -L http://rakudo.org/dl/rakudo/rakudo-moar-2023.08-01-win-x86_64-msvc.zip -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   510    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 79 20.3M   79 16.2M    0     0   459k      0  0:00:45  0:00:36  0:00:09  479k
curl: (18) transfer closed with 4351132 bytes remaining to read
```

**Comment by rawleyfowler** [comment]
Hmm I will mention this to the rakudo.org people. Thanks.

**Comment by rawleyfowler** [comment]
This has been solved by the rakudo team
