### ISSUE TITLE
`zef` is not installed on `windows-latest`

### ISSUE THREAD

**Issue by lizmat** [Raku/setup-raku#36]
Having a script run:

```raku
run "zef", "install", "."
```
results in:
```
Failed to spawn process zef: no such file or directory (error code -4058)
```
whereas that works fine on ubuntu-latest and MacOS-latest.

Example: https://github.com/lizmat/sourcery/actions/runs/9709948595/job/26799645336

**Comment by lizmat** [comment]
@patrickbkr @skaji

**Comment by skaji** [comment]
Maybe
```
run "cmd.exe", "/x/d/c", "zef", "install", ".";
```
works.

**Comment by skaji** [comment]
In windows, `zef` is actually `zef.bat`.

**Comment by lizmat** [comment]
Ahhh... ok, so `$*DISTRO.is-win ?? 'zef.bat' !! 'zef'` indeed does the trick.  Thanks!  Closing.

**Comment by patrickbkr** [comment]
I think this is not the real issue and won't help. AFAI recall, Windows auto completes the '.bat' (in addition to loads of other file extensions) when calling a filename without an extension. This might not be true for all API functions that perform a program call, but for the typical ones it is.

**Comment by lizmat** [comment]
FWIW, it does appear like it does fix the issue: https://github.com/lizmat/sourcery/actions/runs/9714371905 .

So it looks like it doesn't for `run`?
