### ISSUE TITLE
Allow user to use a different docker version of Ubuntu

### ISSUE THREAD

**Issue by tbrowder** [Raku/setup-raku#5]
This may be the wrong place to file the issue, but I would like to somehow use another Ubuntu image.

My problem with the default image is I have to add Perl packages to it before Raku modules are loaded. My Raku module being tested uses Inline:Perl5 and about six Perl modules, and that added configuration takes seven or eight minutes at least.

**Comment by skaji** [comment]
See https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer

**Comment by skaji** [comment]
As you mentioned, this is not an issue for setup-raku, but a general question for GitHub Action.

Maybe you could use IRC or stackoverflow to ask general questions.

So I'll close this issue.
